# base index
set -g base-index 1

# enable 256-colors
set -g default-terminal "screen-256color"

# set window notifications
set -g monitor-activity on
set -g visual-activity on

# automatically set window title
set -g automatic-rename on

# allows for faster key repetition
set -g repeat-time 0

set-option -g status on
set-option -g status-interval 2
set-option -g status-justify "centre"
set-option -g status-left-length 60
set-option -g status-right-length 90

run-shell "powerline-daemon -q"
run-shell "powerline-config tmux setup"

set -g history-limit 100000

set -g mouse on

set -g set-clipboard on

set -sg escape-time 0

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

